global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'plc-core'
    static_configs:
      - targets: ['plc-core:3000']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
